### ISSUE TITLE
AWESOME

### ISSUE THREAD

**Issue by h55nick** [j-mcnally/ember-cli-chrome#5]
was thinking about doing this myself! Glad to see it wasn't an original idea.

questions:
1. do you plan on supporting this?
2. (if yes) are you open to prs?
3. (if yes) can I add a description, point to proper ember-cli etc? 
4. thinking that this should be a different 'build' ie. ember build -e chrome, this would allow the location: #

**Comment by j-mcnally** [comment]
i do want to support it, i will be giving it some much needed update soon. I would love contributors. Ive been taking a break because things were moving so fast in ember-cli land and we were writing a bunch of hacks that now have official stories, so it makes sense to revisit this with a more stable api!

**Comment by h55nick** [comment]
completely understand. ember-cli has been moving crazy fast. I'll try and get the docs and package json updated and play around with it this weekend.
